# Generated by Django 4.1 on 2022-08-11 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="endDate",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="startDate",
            field=models.DateField(blank=True, null=True),
        ),
    ]
