# Generated by Django 4.1 on 2022-08-11 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        ('notes', '0002_note_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookNote',
            fields=[
                ('note_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='notes.note')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookNotes', to='books.book')),
            ],
            bases=('notes.note',),
        ),
    ]
